version: '3.8'

services:
  library:
    image: postgres:latest
    container_name: library
    restart: on-failure
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - library_network

volumes:
  pgdata:


networks:
  library_network:
    driver: bridge
